### ISSUE TITLE
NativeOSX plugin fails to open video

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#182]
**Describe the bug**
Attempting to add .mp4 file using NativeOSX plugin on new installation gives error message.

**To Reproduce**
1. Open Datavyu and add Data using NativeOSX plugin.

**Expected behavior**
Video should open and be ready for playback.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X 10.13.6
 - Datavyu Version 1.5.0rc1

**Additional context**
Did not occur on computer with previous installation of Datavyu. May need fresh install.

Possibly related to #174.

**Comment by Xubes** [comment]
This is caused by having multiple users on a system. If one user installs Datavyu to the Applications folder, only they will be able to unpack the libraries for the NativeOSX plugin. If the install user logs out and another user logs in and tries to run Datavyu, the video will fail to open. See error messages below:

> 16:12:09.694 [AWT-EventQueue-0] ERROR org.datavyu.plugins.nativeosx.NativeOSXPlayer - Unable to load the native library: 
> java.io.FileNotFoundException: /Applications/datavyu.app/Contents/Java/libNativeOSXCanvas.jnilib (Permission denied)
> 	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_172]
> 	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_172]
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_172]
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_172]
> 	at org.datavyu.util.LibraryLoader.extract(LibraryLoader.java:150) ~[ffmpeg-plugin-0.19-SNAPSHOT-mac.jar:?]
> 	at org.datavyu.util.LibraryLoader.extractAndLoad(LibraryLoader.java:115) ~[ffmpeg-plugin-0.19-SNAPSHOT-mac.jar:?]
> 	at org.datavyu.plugins.nativeosx.NativeOSXPlayer.<clinit>(NativeOSXPlayer.java:17) [ffmpeg-plugin-0.19-SNAPSHOT-mac.jar:?]
> 	at org.datavyu.plugins.nativeosx.NativeOSXMediaPlayer.<init>(NativeOSXMediaPlayer.java:38) [ffmpeg-plugin-0.19-SNAPSHOT-mac.jar:?]
> 	at org.datavyu.plugins.nativeosx.AVFoundationMediaPlayer.<init>(AVFoundationMediaPlayer.java:26) [ffmpeg-plugin-0.19-SNAPSHOT-mac.jar:?]
> 	at org.datavyu.plugins.nativeosx.AvFoundationPlayer.<init>(AvFoundationPlayer.java:18) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.plugins.nativeosx.AvFoundationViewer.<init>(AvFoundationViewer.java:22) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.plugins.nativeosx.AvFoundationPlugin.getNewStreamViewer(AvFoundationPlugin.java:73) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.controllers.project.ProjectController.loadProject(ProjectController.java:421) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.views.DatavyuView.createNewSpreadsheet(DatavyuView.java:1659) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.views.DatavyuView.open(DatavyuView.java:1432) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.views.DatavyuView.open(DatavyuView.java:1385) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at org.datavyu.views.DatavyuView$26.actionPerformed(DatavyuView.java:2766) [datavyu-1.5.0-SNAPSHOT-jfx.jar:?]
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_172]
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_172]
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_172]
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_172]
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [?:1.8.0_172]
> 	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125) [?:1.8.0_172]
> 	at java.awt.MenuItem.processActionEvent(MenuItem.java:669) [?:1.8.0_172]
> 	at java.awt.MenuItem.processEvent(MenuItem.java:628) [?:1.8.0_172]
> 	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357) [?:1.8.0_172]
> 	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345) [?:1.8.0_172]
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763) [?:1.8.0_172]
> 	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_172]
> 	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_172]
> 	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_172]
> 	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_172]
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_172]
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) [?:1.8.0_172]
> 	at java.awt.EventQueue$4.run(EventQueue.java:733) [?:1.8.0_172]
> 	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_172]
> 	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_172]
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_172]
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) [?:1.8.0_172]
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_172]
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_172]
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_172]
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_172]
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_172]
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_172]
> 16:12:09.700 [AWT-EventQueue-0] INFO  org.datavyu.plugins.nativeosx.AVFoundationMediaPlayer - Initializing org.datavyu.plugins.nativeosx.AVFoundationMediaPlayer
> Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: org.datavyu.plugins.nativeosx.NativeOSXPlayer.addNativeOSXCoreAnimationLayer(Ljava/lang/String;)V
> 	at org.datavyu.plugins.nativeosx.NativeOSXPlayer.addNativeOSXCoreAnimationLayer(Native Method)
> 	at org.datavyu.plugins.nativeosx.NativeOSXPlayer.addNotify(NativeOSXPlayer.java:29)
> 	at java.awt.Container.addImpl(Container.java:1124)
> 	at java.awt.Container.add(Container.java:1007)
> 	at javax.swing.JDialog.addImpl(JDialog.java:921)
> 	at java.awt.Container.add(Container.java:975)
> 	at org.datavyu.plugins.nativeosx.AVFoundationMediaPlayer.init(AVFoundationMediaPlayer.java:47)
> 	at org.datavyu.plugins.nativeosx.AvFoundationPlayer.<init>(AvFoundationPlayer.java:19)
> 	at org.datavyu.plugins.nativeosx.AvFoundationViewer.<init>(AvFoundationViewer.java:22)
> 	at org.datavyu.plugins.nativeosx.AvFoundationPlugin.getNewStreamViewer(AvFoundationPlugin.java:73)
> 	at org.datavyu.controllers.project.ProjectController.loadProject(ProjectController.java:421)
> 	at org.datavyu.views.DatavyuView.createNewSpreadsheet(DatavyuView.java:1659)
> 	at org.datavyu.views.DatavyuView.open(DatavyuView.java:1432)
> 	at org.datavyu.views.DatavyuView.open(DatavyuView.java:1385)
> 	at org.datavyu.views.DatavyuView$26.actionPerformed(DatavyuView.java:2766)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
> 	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
> 	at java.awt.MenuItem.processEvent(MenuItem.java:628)
> 	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
> 	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Warning: SidebarTreeModel uses default user items.
> Warning: class ch.randelshofer.quaqua.osx.OSXImageIO could load library null but can't use it. java.lang.UnsatisfiedLinkError: ch.randelshofer.quaqua.osx.OSXImageIO.nativeGetNativeCodeVersion()I
> 16:12:09.724 [AWT-EventQueue-0] INFO  org.datavyu.views.VideoController - Stop.
> 16:12:09.724 [AWT-EventQueue-0] DEBUG org.datavyu.util.ClockTimer - Setting Clock Rate to 0.0X
> 16:12:09.724 [AWT-EventQueue-0] INFO  org.datavyu.views.VideoController - Forced sync
> 16:12:09.724 [AWT-EventQueue-0] INFO  org.datavyu.views.VideoController - Stop.
> 16:12:09.724 [AWT-EventQueue-0] DEBUG org.datavyu.util.ClockTimer - Setting Clock Rate to 0.0X
> 16:12:09.726 [AWT-EventQueue-0] DEBUG org.datavyu.plugins.StreamViewerDialog - Clock setting rate of track: Identifier: 0 to 0.0X
> 16:12:09.726 [AWT-EventQueue-0] INFO  org.datavyu.plugins.nativeosx.AvFoundationViewer - Setting playback speed to: 0.0X
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> 	at org.datavyu.plugins.nativeosx.AvFoundationViewer.isSeekPlaybackEnabled(AvFoundationViewer.java:131)
> 	at org.datavyu.plugins.nativeosx.AvFoundationViewer.setRate(AvFoundationViewer.java:48)
> 	at org.datavyu.plugins.StreamViewerDialog.clockRate(StreamViewerDialog.java:678)
> 	at org.datavyu.util.ClockTimer.notifyRate(ClockTimer.java:354)
> 	at org.datavyu.util.ClockTimer.setRate(ClockTimer.java:211)
> 	at org.datavyu.views.VideoController.stopAction(VideoController.java:1397)
> 	at org.datavyu.views.DatavyuView$6.stateChanged(DatavyuView.java:626)
> 	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
> 	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
> 	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
> 	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
> 	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
> 	at javax.swing.JTabbedPane.removeTabAt(JTabbedPane.java:975)
> 	at javax.swing.JTabbedPane.remove(JTabbedPane.java:1051)
> 	at org.datavyu.views.DatavyuView$OpenTask$1.run(DatavyuView.java:2844)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>

**Comment by JeffSpies** [comment]
This seems like it would have been relevant for past versions of DV. Are we sure this is limited to the RC?

**Comment by JeffSpies** [comment]
Update: only relevant for 1.5.0rc1

**Comment by Xubes** [comment]
@JeffSpies It was indeed present before and was not introduced in 1.5. I filed this under the 1.5 project/milestone so that it shows up to @TheoWolf. Feel free to move to another milestone.

**Comment by TheoWolf** [comment]
@Xubes @JeffSpies I will move this to 1.5.1 Project -> 1.5.1-RC1 Milestone

**Comment by Mase3206** [comment]
Happy 2024, y'all. I work at the IT help desk at the University of Montana. A faculty member was still experiencing this issue a few weeks ago. The milestone attached to this issue was passed a while ago, but this issue is still open and the changelogs don't say whether or not it was patched. Any updates on this?
